export default {
    backUrl: {
        module: "/back_module",
        table: '/back_table',
        table_concrete: '/back_table/{id}',
        column: '/back_column',
        content: '/back_content',
        content_concrete: '/back_content/{id}',
        character: '/back_character',
        character_concrete: '/back_character/',
        human: '/back_human',
        human_concrete: '/back_human/',
        depart: '/back_depart',
        depart_concrete: '/back_depart/',
        section: '/back_section',
        section_concrete: '/back_section/',
        organization_tree: '/back_organization',
        request: '/back_request',
        request_concrete: '/back_request/',
        workflow: '/back_workflow',
        workflow_concrete: '/back_workflow/',
        workflow_node: '/back_workflow_node',
        workflow_node_concrete: '/back_workflow_node/',
        workflow_route: '/back_workflow_route',
        workflow_route_concrete: '/back_workflow_route/'
    },
    frontUrl: {
        human: "/human_resouce",
        humanResource: "/human_resouce/",
        depart: "/depart",
        depart_concrete: "/depart/",
        section: "/section",
        section_concrete: "/section/",
        content_concrete: '/content/',
        form_concrete: '/form/',
        organization_tree: '/organization',
        workflow: '/workflow',
        request_self: '/request_self',
        request_done: '/request_done',
        request_backlog: '/request_backlog',
        request_concrete: '/request/'
    }
}