export default {
    backUrl:{
        module:"/back_module",
        table:'/back_table',
        table_concrete:'/back_table/{id}',
        column:'/back_column',
        content:'/back_content',
        content_concrete:'/back_content/{id}',
        character:'/back_character',
        character_concrete:'/back_character/',
        human:'/back_human',
        human_concrete:'/back_human/',
        depart:'/back_depart',
        depart_concrete:'/back_depart/',
        section:'/back_section',
        section_concrete:'/back_section/',
        organization_tree : '/back_organization',
    },
    frontUrl:{
        human:"/human_resouce",
        humanResource:"/human_resouce/",
        depart:"/depart",
        depart_concrete:"/depart/",
        section:"/section",
        section_concrete:"/section/",
        content_concrete:'/content/',
        form_concrete:'/form/',
        organization_tree : '/organization',
    }
}